cryptosharks131/lndg

- nginx.sh
Listening to port (only) and `server_name=_` allows lndg to bind to the ip address that might be reassigned on restart.
*I also had to `systemctl daemon-reload` multiple times for uwsgi to start properly.  But that started working before I traced it down.
> Glob nginx to whatever IP is assigned on reboot.

- gui/templates/channel.html
- gui/templates/home.html
- gui/templates/invoices.html
- gui/templates/payments.html
- gui/templates/pending_htlcs.html
- gui/views.py
- jobs.py
> #124 Show inflight htlc route

- gui/views.py
If bos gift is used to distribute gifts via routing fees, it skews the rebalance rate on the channel card. To fix amounts smaller than 1000 sats are ignored for rebalance ppm purpose.
> Channel Card : ignore gift payments from rebal rate

- gui/templates/route.html
- gui/views.py
For an on-going payment/rebalance it is good to see the outgoing and incoming HTLCs. Specially the incoming HTLC which indicates availability of liquidity.
> Route : Show associated pending HTLC for the route if available

- jobs.py
AR target is increased by 21% up to 2*AR-Target% after successful rebalances.
AR target is reduced to available liquidity accounting for MPP payments, subject to minimum of 69420 or ar_amt_target after failed rebalances. Available liquidity is estimated when the failure originates from our own node. 
Together with randomness introduced by AR variance, this would produce distinct rebalance amounts in subsequent rebalances in line with last known available liquidity.
> AR : Auto adjust ar target

- gui/templates/channel.html
- gui/templates/home.html
- gui/templates/rebalances.html
- gui/templates/rebalancing.html
- gui/views.py
Show payment hash on rebalance pages to take to route page.
Also show successful rebalances in a separate section.
> Show payment hash on rebalance pages with link to route

- rebalancer.py
This would be useful for channels which are always required on local (LOOP) or used for manual work flow (wos -> On-Chain -> LOOP) or channels like kraken which are used for managing manual payments to/from exchange.
> AP - Do not disable ar_out_target 100 channels for AR if enabled

- jobs.py
- rebalancer.py
Rapid Fire increase by 21% for each success and down to half (until 69420) for each failure without impacting AR Target Amt. This allows a cleaner and more efficient sweep during rebalance for all available liquidity.
While adding rebalance, peers with higher remote balance are prioritised.
> Rapidfire up/down + prioritise remote balance for rebalance

- gui/forms.py
- gui/templates/home.html
- gui/urls.py
- gui/views.py
This PR removes the Update Channel Policy part from the Dashboard. Going to the Advanced Settings or Fee Rates page is much more convenient if anyone wants to change fees or CLTV for their channels.
> Remove Update Channel Policy from the Dashboard

- htlc_stream.py
HTLC Failure Stream feature stores only `link_fail_event` which is related to the forwarding node failure itself. I would like to store `forward_fail_event` as well so that I can investigate which downstream nodes return forwarding failures.
> Add forward fail event

- gui/static/w3style.css
- gui/templates/advanced.html
- gui/templates/home.html
- gui/templates/rebalancing.html
This PR fixes the position of the capacity label in the liquidity bar when outbound liquidity is low and for when the user uses a different zoom setting.
Issue:
> Fix capacity position liq bar

- gui/static/w3style.css
- gui/templates/home.html
This PR improves readability of the home page statistics by:
- Adding tables to better visualize liquidity usage, costs, balance, etc.
- Adding colors/tags to show sync status of LND and chain
- Compacting statistics header overview
- css styles
- Add copy address button
Screenshots:
> Statistics header improvements

- gui/forms.py
- gui/templates/home.html
- gui/templates/local_settings.html
- gui/templates/rebalancing.html
- gui/views.py
This PR adds a `local-settings.html` component so it can be reused across other pages in a way that:
- local settings table view can be removed since the form already contains the current values to be edited
- the form can be reused across other local settings forms as part of future development (i.e `advanced`, `fees`...)
- the form is responsive and suitable to smaller screens
- only update changes that has been actually changed from `db_value`
screenshot:
> Add local_settings form component

- gui/static/w3style.css
- gui/templates/advanced.html
- gui/templates/home.html
- gui/templates/rebalancing.html
Remove progress bar element (poor corss-browser api/support) and fix table sorting order.
Tested on: chrome, firefox, safari(mobile), edge
PS: Fix copy button position overlay and renamed profit column to `Profit/Outbound`
> Fix liquidity bar cross-browser issue and table sorting order

- gui/views.py
- htlc_stream.py
-Reduces the documented available liquidity at the time the failed HTLC occurred
-Clean-up query annotations and eliminate some loops
> Reduce Failed HTLCs Out Liq by Chan Reserve

- rebalancer.py
-Fixes issues for `406` status code rebalances that don't trigger another rebalance after the wait time
-Fixes an issue that causes manual rebalances and requests to wait until the rebalancer exits before being processed
> Fix Rebal Issues

- gui/templates/base.html
- rebalancer.py
-Fixes issues for `406` status code rebalances that don't trigger another rebalance after the wait time
-Fixes an issue that causes manual rebalances and requests to wait until the rebalancer exits before being processed
> Fix Rebalancing Issues - v1.6.4

- gui/views.py
`Rocket Node` via Telegram: 
> On the /actions page.. the link for the peer alias doesn't include the nodeid
This PR fixes a small bug by populating the peer's pubkey on `/actions` page.
> [bug] actions: add missing node pubkey

- gui/templates/base.html
- gui/templates/home.html
- gui/templates/rebalances_table.html
- gui/urls.py
- gui/views.py
This PR adds a new endpoint `api/node_info` to periodically retrieve dynamic data from lnd grpc calls.
Notes:
- periodic calls are 21 seconds cycle
- these calls are only made if browser tab is active (it stops requesting new data from api if tab is not visible)
- failed HTLCs & invoices are also not updated each cycle (I believe it would be an overhead with little gain in usefulness + their info do not help in building derived info such as: cost, routed, fees, etc)
> Add Home auto refresh from API

- gui/templates/home.html
- gui/urls.py
- gui/views.py
-Summarize forwards when loading the home page in order to reduce the data that must be sent from server to client
-Addresses slow loading that occurs when many forwards have been processed in the last 7 days
> Summarize Forwards On Home Load

- jobs.py
- rebalancer.py
A configurable setting is added to allow disconnecting peers who have expiring HTLC within 13 (default) blocks. Can be set via settings. Setting to 0 will disable the feature.
> Disconnect Peers with expiring htlc within 13 blocks

- gui/templates/base.html
Adds the attempted PPM calculation as a parenthetical note to `Fee Insufficient` HTLC failure reason.
> show attempted PPM when HTLC failure reason is Fee Insufficient

- rebalancer.py
I'm running non-MPP for 48h on my main node and it's working fine. 
This proposed change intends to reduce the number of HTLC shards LNDg fires to rebalance.
- mitigates the risk for this LND bug: https://github.com/lightningnetwork/lnd/issues/7657
- additional benefit might be a reduction in base-fees
Up for review, thanks
> Disable mpp until LND race condition is resolved

- Dockerfile
- controller.py
- docker-compose.yaml
- gui/views.py
- initialize.py
- manage.py
This allows to:
- remove the need to use **supervisord** on _docker containers_
- allows graceful exiting when executing `docker stop` or `^C`
- unifies _manage.py_ and _controller.py_ and therefore unifies logs
- potentially simplifies manual installs (?)
It's possible to run the entire application by using: `python controller.py runserver <addr:port>`
Note: using python:3-alpine reduces the container size from 1.3GB to 352MB in my tests
> Unify logs

- jobs.py
The new fields added with the addition of inbound fees in LND (see https://docs.lightning.engineering/lightning-network-tools/lnd/inbound-channel-fees) were not being handled properly in case of an `edge not found` error being return from the `GetChanInfo` call, employed in the `update_channels` job.
This would prevent channels proceeding the problematic channels in question to not be properly added to the lndg database.
> jobs: update_channels: handle inbound fees on getchaninfo failures

- af.py
Group by peer pubkey while running AF calculations to accommodate having multiple channels with the same peer.
Needs more data validation.
> AutoFees Group By Pubkeys

- gui/views.py
- requirements.txt
Replaced the previous shell-based approach for retrieving the remote `channel.db` file size with a more robust and secure solution using the `paramiko` SSH library.
**Why this is better:**
*   **Security:** Avoids shell pipe vulnerabilities (e.g., command injection).
*   **Reliability:** Uses a dedicated SSH library (`paramiko`) for more stable and predictable connections.
*   **Efficiency:** Only imports `paramiko` if remote file size retrieval is enabled.
*   **Flexibility:**  Provides separate settings for host, user, port, and path.
This feature is disabled by default. To enable it and retrieve the `channel.db` size from a remote LND node:
1.  **Enable the Feature:**
*   Go to `https://<your-lndg-instance>/api/settings/RemoteFSEnabled/`
*   Set the `value` to `1`.
2.  **Refresh the …
> Add function to retrieve channel.db file size with LND remote suppor

- gui/templates/unprofitable_channels.html
- gui/views.py
Hey @cryptosharks131 ,
this PR adds "Age" to Unprofitable Channels:
- Calculates the approximate age (in days) for each channel.
- Uses the age to give newer channels (less than 30 days, with a bigger bonus for < 7 days) a break on the "Stuck Index" so they don't immediately look bad.
- Added an "Age (Days)" column to the table so you can see it.
Should make the unprofitable view a bit smarter for new channels and fix the remote DB size stuff. Let me know what you think!
> Sort by stuck index per default & add channel age as an influencing metric for unprofitable channels
