- gui/templates/home.html
- gui/templates/open_list.html
- gui/urls.py
- gui/views.py
Add link to page with a suggested open list based on payments your node has sent through the network
> Suggested open list

- gui/forms.py
- gui/serializers.py
- gui/templates/testnet.html
- gui/views.py
Close with channel id, clean up pending channels tables, include testnet page links
> Close with chan id and some small enhancements

- README.md
Extending description of manual docker installation steps (docker-compose.yaml) for custom/bare metal setups.
> added docker instructions for custom setup

- .gitignore
- gui/templates/failed_htlcs.html
- gui/templates/home.html
- gui/urls.py
- gui/views.py
Shows the last 150 failed HTLCs
> Add Failed HTLCs page

- gui/templates/base.html
Noticed this after testing upgrade within myNode. I thought the upgrade had failed, but things seems fine.
> Bump version to v1.1.2

- initialize.py
Would be nice to be able to set the admin username. Most Citadel apps have the default username "citadel" and it's confusing for users to have different usernames for each app.
> Add adminuser option

- gui/forms.py
- gui/templates/advanced.html
- gui/templates/home.html
- gui/templates/rebalancing.html
- gui/views.py
- rebalancer.py
> #86 Add Configurable Auto Pilot Days

- gui/templates/failed_htlcs.html
- gui/templates/pending_htlcs.html
- gui/templates/route.html
> GUI : Display Channel ID as hyperlink on all pages to allow channel card quick link #95

- gui/templates/channel.html
- gui/templates/home.html
- gui/templates/rebalancing.html
- rebalancer.py
> Rebalance : Display Actual Fee Paid for rebalance #97

- gui/templates/open_list.html
- gui/templates/route.html
- gui/urls.py
- gui/views.py
> OPENS: Open Peer list to show last 69 payment routes for the suggested peer

- jobs.py
ReconectPeer LastReconnect Time was not updated in case of failures.
> Jobs: reconnect peer to correctly update last reconnected time

- gui/templates/route.html
- gui/views.py
If a rebalance and invoice is associated with the payment hash, show on the route page.
> Route: Show Associated rebalance and invoice for route if available

- gui/templates/failed_htlcs.html
- gui/templates/home.html
- gui/views.py
Page now allows to see all failures originated from or to a selected channel alias.
> Failed_HTLCs : Filter Failed HTLC based on channel alias selected

- jobs.py
1- increase by 11% instead of 21% if successful non-rapid fire rebalance (this would slow down increase)
2- catch-all condition will be added for non-rapid fire failed rebalances to reduce the ar target amount by half. This means every failed non-rapid fire rebalance will half the AR Target Amt
> Catch-all AR Reduction on Failure

- gui/templates/autofees.html
- gui/templates/channel.html
- gui/views.py
- jobs.py
Detect Manual and External local fee change to the channel and record in auto fee log for a trace of local fee changes.
> [AutoFeeLog] : Detect Manual and External Fee Change 

- gui/templates/rebalancing.html
- gui/views.py
A quick filter on the rebalancing page to only see source (potential) and sinks.
> [rebalancing] : rebalancing page filter for sink and source

- gui/templates/home.html
- gui/templates/rebalancing.html
- gui/views.py
This pull request fixes some merge conflicts from previous pull requests and:
-Replicates ui/ux of the main active channels table to other tables
-Moves select all channels checkbox to table header
-Adds tags/buttons to other fields such as public addresses and private liquidity statistcs
-Adds on-click copy functionality to public addresses
-Adds enable/disable AR to main active channels table
In Rebalancing screen:
-Applies same table format from the home screen tables
-Simplifies AR actions by merging In/Out status with Enable/Disable AR
-General improvements
> Feature/update UI/updates

- gui/templates/failed_htlcs.html
- gui/templates/rebalancing.html
Links to filter for sink/source after the latest GUI change.
> rebalancing page filter for sink and source merge with gui changes

- gui/lnd_deps/lnd_connect.py
- gui/templates/advanced.html
- gui/views.py
- rebalancer.py
- requirements.txt
Updates the rebalancer to allow multiple rebalances to be ran at once by increasing the `AR-Workers` rebalancer setting on the `/advanced` page.
> Async rebalancing

- gui/views.py
Change default GUI-GraphLinks to amboss.space since it's much wider used than 1ml.com
> Change default GUI-GraphLinks to amboss.space

- gui/templates/batch.html
- gui/views.py
Adds simple on chain balance calculation
> Add on chain balance calc to batch open channels

- gui/templates/home.html
> Move "refresh page message" to the top right corner

- gui/static/w3style.css
Fix dark-mode hover by adding !important rule
> Dark mode hover patch

- gui/static/w3style.css
- gui/templates/action_list.html
- gui/templates/advanced.html
- gui/templates/fee_rates.html
- gui/templates/home.html
- gui/templates/rebalancing.html
- Fixes missing pages with the new liquidity bar layout
- Changes remote lquidity color to grey
- Small adjustments on home page
> Liquidity bar: missing pages

- gui/static/w3style.css
- gui/templates/base.html
- gui/templates/home.html
- gui/templates/local_settings.html
- Adds github-ish like highlighting and `Ctrl+Shift+E` shortcut to hide sensitive data ( `E` for "encryption")
> Feature - dark mode improvements

- gui/static/api.js
- gui/static/w3style.css
- gui/templates/base.html
Remove auto hide messages since we've added close message functionality
> Remove disappearing messages

- gui/serializers.py
- gui/static/api.js
- gui/templates/rebalancing.html
- gui/urls.py
- gui/views.py
-API that returns success rates in the last 7 days
> Rebal stats api

- gui/views.py
- rebalancer.py
-Manual rebalancer issue when not using a last hop pubkey
-Rebalancer can become stuck in some cases
> Rebalancer fixes

- gui/serializers.py
- gui/templates/addresses.html
- gui/templates/balances.html
- gui/urls.py
- gui/views.py
+PendingSweeps
+PublishTransaction
+ListAddresses
> Additional wallet tools

- gui/templates/balances.html
Calculator to help price a cpfp sweep tx
> Fee estimation for cpfp

- gui/templates/base.html
- gui/templates/channel.html
- gui/templates/home.html
Share js template obj across other pages
> Forwards template sharing

- gui/templates/rebalances.html
- gui/templates/rebalances_table.html
To help with easier view of pending and inflight requests.
> Show Inflight and Pending Rebalances separately

- gui/templates/base.html
- gui/templates/home.html
> [Routed table] Add icons & split `in` and `out`

- README.md
- controller.py
- gui/af.py
- htlc_stream.py
- initialize.py
- jobs.py
- nginx.sh
- rebalancer.py
- systemd.md
- systemd.sh
- Unifies backend to a single point of entry, adding additional processes becomes easier
- Common logging format across processes and a single logging output
- Update documentation for a single service setup plus additional updates
- Update automated scripts for single service setup
- Add LNDg install check to nginx and systemd scripts
- The initialize.py will now setup supervisord to log to the data folder and allows forced replacement of existing settings files
- Fixed an af issue for balanced channels to increase on large net out vs. capacity
> Unify Backend With Single Controller

- gui/static/w3style.css
- gui/templates/home.html
- gui/templates/logs.html
- gui/urls.py
- gui/views.py
> Add `/logs` page

- keysend.py
> Add command line args to keysend

- gui/templates/advanced.html
- gui/templates/home.html
Let LND fails if the fee user has provided is beyond expected (I had to use lncli to put the fee i wanted)
> Remove max base fee limit

- gui/templates/local_settings.html
- gui/views.py
This PR fixes:
- the selected option is always off on page refresh
- when updating any single setting, all settings were getting updated as well
> Fix settings form

- gui/templates/home.html
Switch inbound - outbound columns of ratio table to reflect order of active / inactive / pending channels tables below.
> home: switch inbound / outbound in ratio table

- rebalancer.py
Do not try rebalancing when Last Hop's iRate > AR Max Fee Rate parameter
> Enforce AR Max Fee Rate

- jobs.py
> Simple typo fix in jobs.py

- README.md
Thought about this for a while, that a TOC would be helpful due to the length of the readme.
Lmk what you think
> Proposing new Readme cleanup & added a TOC

- gui/templates/unprofitable_channels.html
added a more cumbersome but more compatible fallback routine.
To be tested, I don't have a local non-SSL setup available
>  clipboard copy functionality fallback to work on local / non SSL environment.
